# Generated by Django 4.2.6 on 2024-02-01 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_date', models.DateField(null=True)),
                ('casual_leave', models.IntegerField(blank=True, default=0, null=True)),
                ('month', models.CharField(max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, default=0, null=True)),
                ('leave', models.IntegerField(blank=True, default=0, null=True)),
                ('conveyance_allowance', models.IntegerField(blank=True, default=0, null=True)),
                ('hra', models.IntegerField(blank=True, default=0, null=True)),
                ('other_allowance', models.IntegerField(blank=True, default=0, null=True)),
                ('total_working_days', models.IntegerField(blank=True, default=0, null=True)),
                ('other_cuttings', models.IntegerField(blank=True, default=0, null=True)),
                ('add_bonus', models.IntegerField(blank=True, default=0, null=True)),
                ('holiday', models.IntegerField(blank=True, default=0, null=True)),
                ('salary', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.payroll_employee')),
            ],
        ),
    ]
